var translate = function(key){
    switch (key) {
        case 'workTypeId':
            return 'WTI'; 
        case 'workType':
            return 'WT';
        case 'image':
            return 'IM';
        case 'name':
            return 'Na';
        case 'clossedSizes':
            return 'CS';
        case 'quantities':
            return 'Qs';
        case 'mandatoryFinishes':
            return 'MFG';
        case 'groupName':
            return 'GN';
        case 'finishes':
            return 'F';
        case 'finish':
            return 'f';
        case 'comment':
            return 'FC';
        case 'showToClientFinish':
            return 'SCF';
        case 'showToClient':
            return 'SC';
        case 'incidences':
            return 'In';
        case 'itemId':
            return 'IId';
        case 'type':
            return 'T';
        case 'action':
            return 'A';
        case 'values':
            return 'V';
        case 'items':
            return 'I';
        case 'bleedPrint':
            return 'BP';
        case 'ink':
            return 'Ik';
        case 'inksDetails':
            return 'ID';
        case 'openedSize':
            return 'OZ';
        case 'allTheSame':
            return 'AS';
        case 'optionalFinishes':
            return 'OF';
        case 'quantityOfPages':
            return 'QP';
        case 'quantityOfVias':
            return 'QV';
        case 'quantityOfSheets':
            return 'QT';
        case 'faces':
            return 'Fa';
        case 'material':
            return 'M';
        case 'paper':
            return 'P';
        case 'price':
            return 'Pr';
        case 'inksQuantity':
            return 'IQ';
        case 'clossedSize':
            return 'CZ';
        case 'optionalFinishesPrices':
            return 'OFP';
        case 'quantity':
            return 'Q';
        case 'workId':
            return 'WI';
        case 'prices':
            return 'Prs';
        case 'cutsPerSheet':
            return 'CPS';
        case 'excess':
            return 'E';
        case 'machine':
            return 'Ma';
        case 'paperSize':
            return 'PZ';
        case 'quantityPerPaper':
            return 'QPP';
        case 'sheetSize':
            return 'S';
        case 'totalPrice':
            return 'TP';
        case 'internalInformation':
            return 'II';
        case 'Ordinal':
            return 'O';
        case 'processDetails':
            return 'PD';
        case 'priceWithFinishes':
            return 'PF';
        default:
            return key;
    }
}

var deTranslate = function(key){
    switch (key) {
        case 'WTI': 
            return 'workTypeId';
        case 'WT':
            return 'workType';
        case 'IM':
            return 'image';
        case 'Na':
            return 'name';
        case 'CS':
            return 'clossedSizes';
        case 'Qs':
            return 'quantities';
        case 'MFG':
            return 'mandatoryFinishes';
        case 'GN':
            return 'groupName';
        case 'F':
            return 'finishes';
        case 'f':
            return 'finish';
        case 'FC':
            return 'comment';
        case 'SCF':
            return 'showToClientFinish';
        case 'SC':
            return 'showToClient';
        case 'In':
            return 'incidences';
        case 'IId':
            return 'itemId';
        case 'T':
            return 'type';
        case 'A':
            return 'action';
        case 'V':
            return 'values';
        case 'I':
            return 'items';
        case 'BP':
            return 'bleedPrint';
        case 'Ik':
            return 'ink';
        case 'ID':
            return 'inksDetails';
        case 'OZ':
            return 'openedSize';
        case 'AS':
            return 'allTheSame';
        case 'OF':
            return 'optionalFinishes';
        case 'QP':
            return 'quantityOfPages';
        case 'QV':
            return 'quantityOfVias';
        case 'QT':
            return 'quantityOfSheets';
        case 'Fa':
            return 'faces';
        case 'M':
            return 'material';
        case 'P':
            return 'paper';
        case 'Pr':
            return 'price';
        case 'IQ':
            return 'inksQuantity';
        case 'CZ':
            return 'clossedSize';
        case 'OFP':
            return 'optionalFinishesPrices';
        case 'Q':
            return 'quantity';
        case 'WI':
            return 'workId';
        case 'Prs':
            return 'prices';
        case 'CPS':
            return 'cutsPerSheet';
        case 'E':
            return 'excess';
        case 'Ma':
            return 'machine';
        case 'PZ':
            return 'paperSize';
        case 'QPP':
            return 'quantityPerPaper';
        case 'S':
            return 'sheetSize';
        case 'TP':
            return 'totalPrice';
        case 'II':
            return 'internalInformation';
        case 'O':
            return 'Ordinal';
        case 'PD':
            return 'processDetails';
        case 'PF':
            return 'priceWithFinishes';
        default:
            return key;
    }
}